### ISSUE TITLE
Doc on how users, roles and logins are handled?

### ISSUE THREAD

**Issue by JoeMurray** [civicrm/civicrm-standalone#5]
If there could be a couple of lines about how users and roles and logins are handled, which I think are the only real dependencies of CiviCRM on a CMS, that would be great. Eg We use entries in uf_match table as users and they are created by you in code. The only supported roles are those created by ACLs. The only supported login process is OAuth, where CiviCRM standalone is the client. Or whatever is accurate.

**Comment by mlutfy** [comment]
Opened an issue here with a few discussion points: https://lab.civicrm.org/dev/core/-/issues/4053
